### ISSUE TITLE
Pre/post build steps - are ignore by default, please make this configurable

### ISSUE THREAD

**Issue by duaneellissd** [eclipse-embed-cdt-move/eclipse-plugins#374]
This is a feature change/request

Currently, when pre/post build steps are created during Makefile generation, they are done such that all errors are ignored. This is by by design, and IMHO very poor design.

my request is simply this:  Please make this a configurable option, if desired - this could be  “ignore by default”

A very simple use case:
    I need to run a “post build step” that converts the ELF or HEX file into some other format that is usable by my flash update/upgrade ability. For example, my flash utility needs to check a CRC value, and/or a checksum and/or other signatures that are part of the download.  Normally a post processing script would do this.

    Another example is this: I have some small data files that need to be converted (ie: binary to C file (a giant array of bytes).

Sometimes things go wrong and these tools report errors, but Eclipse ignores these errors.

https://stackoverflow.com/questions/28881290/how-to-stop-compliation-if-a-pre-build-step-fails-in-eclipse

**Comment by ilg-ul** [comment]
Unfortunately the pre/post build steps are handled by the Eclipse CDT and the GME plug-ins have no control on error processing.
