### ISSUE TITLE
How to pass program parameters via semihosting?

### ISSUE THREAD

**Issue by cdwilson** [eclipse-embed-cdt-move/eclipse-plugins#377]
The blinky example dumps the args passed to main:

```
int
main(int argc, char* argv[])
{
  // Show the program parameters (passed via semihosting).
  // Output is via the semihosting output channel.
  trace_dump_args(argc, argv);
```

However, I can't find any documentation that describes how to actually pass custom parameters.  Can you describe how to pass custom parameters via semihosting?

**Comment by ilg-ul** [comment]
https://xpack.github.io/qemu-arm/options/

**Comment by ilg-ul** [comment]
For questions and support, please use the project forum.
